### ISSUE TITLE
Propose what participant 'states' we need record and/or surface to schools

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/ecf2#114]
## Why?
In ECF1 we currently have a host of statuses that are used to flag various states of e.g. whether a participant is eligible or waiting for confirmation on eligibility. These statuses are known to be unclear and confusing. For ECF 2 we need to understand what statuses we need to record either for DfE purposes or for surfacing to schools.

## What?
- Team sessions to consider user needs and scenarios that may need a status to reflect
- Create a proposal for statuses
- Hand over for content design

## Helpful links or other information
[Old UR playback on statuses](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/Shared%20Documents/Teacher%20Continuing%20Professional%20Development/Teacher%20CPD%20Team/Schools%20and%20Teachers%20Team/User%20Research/2.%20Research%20rounds%20(all)/Round%2017%20-%20Schools%20visits%20and%20online%20cohortless%20dashboard/Dashboard%20redesign%20playback.pptx?d=w6eee70e73dab50ddd3323ccf4faf3560&csf=1&web=1&e=cRhebb)

```mermaid
stateDiagram
[*] --> [In_progress_registration]
    [In_progress_registration]  --> [Registered_without_mentor]
    [Registered_without_mentor] --> [Registered_with_mentor]
    [Registered_with_mentor] --> [Registered_without_mentor]
    [Registered_with_mentor] --> [Completed_training]
```

**Comment by peteryates** [comment]
Here's [the status determining code](https://github.com/DFE-Digital/early-careers-framework/blob/main/app/services/training_record_state.rb#L105) 😬

**Comment by mason-emily** [comment]
https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=H~.9XOamrT~x&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6

**Comment by claire-hughez** [comment]
flowchart TD
    in_progress[In progress registration]  --> registered_without_mentor[Registered without mentor]
    registered_without_mentor --> registered_with_mentor[Registered with mentor]
    registered_with_mentor --> registered_without_mentor
    registered_without_mentor --> completed_training[Completed training]

**Comment by gracecbrennan** [comment]
@claire-hughez and @tonyheadford going to look at this together today

**Comment by peteryates** [comment]
@tonyheadford and I have thrown some ideas down, based on the pink post-its in the linked Lucid board.

## Transfer states

- Leaving school
- Left school
- Joining a school
- Joined school

We should be able to get all this information from `ECTAtSchoolPeriod` and
`MentorAtSchoolPeriod` providing we record a future leaving date when the
participant is scheduled to leave.

## DQT/TRS matching

We won't allow a teacher who doesn't appear in the DQT to be
registered, we can store a timestamp/event when they were matched.

Active flags/alerts appear on the DQT record and indicate someone currently
isn't eligible.

## ECT

### Induction

- Eligible for induction
- Undertaking induction
- Paused
- Completed
- Ineligible
- Waiting for AB to record induction start date
- Waiting for QTS

These should probably be split and stored at the teacher level:

- **Eligibility status**
  * eligible
  * ineligible
- **Induction status**:
  * not started
  * ongoing
  * complete
  * deferred

### Training

- Eligible for funded FIP/provider led training
- Eligible for funded CIP/school led training

Are these school level states?

- Undertaking ECT training
- Completed ECT training (based on declarations)

Similar to induction, these sound like states on the teacher
record. Possibly another state to indicate they're no longer
teaching.

## Mentor

### Mentor training

- Eligible for funded mentor training
- 3 years expired

Not 100% sure how we need to take the 3 years rule into account, but it sounds
like it's a factor in working out whether or not they're eligible for funding.
Eligibility to be stored separately from training state.

- Undertaking mentor training
- Completed mentor training

These are statuses similar to the induction states.

### Mentoring

Can be deduced from `Mentorship` and if there are any ongoing ones. This applies
to both ECTs and mentors.

## Participants

- All details
- Missing details

Do we need a 'onboarding' status? Depends on how the journey/process looks.

## Training

- Training deferred
- Withdrawn from training
- Training part time
- Training full time

Full time/part time could be recorded on the `ECTAtSchoolPeriod` or
`MentorAtSchoolPeriod`.

Deferred, withdrawn sound like they could be closure statuses on the
`TrainingPeriod`, i.e., a training period was closed because it was
deferred (or withdrawn)

**Comment by claire-hughez** [comment]
This is great, thank you guys!

> registered, we can store a timestamp/event when they were matched.

Would we need to store a timestamp for when we re-check DQT for any other updates too? E.g. when an induction start date is given later, or QTS is finally achieved.

Do we want to define as 'registered' when an ECT doesn't have a QTS date or induction start date?

> Induction status:

Why do these need to differ from the AB portal statuses? This feels like it's missing when they've passed, failed, etc? Feels like the status should be the same across both and these wouldn't meet all our needs.

> Are these school level states?

I think so but we can check with Emily M when she's back.

> Do we need a 'onboarding' status? Depends on how the journey/process looks.
In other services I've seen this defined sometimes as a state or as a time stamp, e.g. registration_complete_at, compared to registration_started or registration_updated_at.

It feels here there needs to be a design/product decision of when we allow users to save registration and remember it as a draft record to go back to, or if they have to go through the full flow to have the record saved?

**Comment by gracecbrennan** [comment]
This is something we will be working out as we go. 

@mason-emily to take a look when she is back but move to done for now.
